# 
# Spawn coords storage
debug: false

spawn:
  x: 0
  y: 256
  z: 0
  yaw: 0
  pitch: 0
  
options:
  world: world
  disable-plantGrowth: true
  disable-weather: true
  disable-dayLightCycle: true
  
  mob-spawning:
    disable-mobSpawning: true
    # Modes: natural, all, off
    # Natural stops all natural spawns
    # All stops ALL mob spawns
    # Off allows all mobs to spawn
    mode: natural
  
  custom-joinmsg: ' '
  custom-leavemsg: ' '
  
  build:
    disable-block-break: true
    block-break-msg: '&f[&6Lobby&f] You''re not allowed to do that here!'
    
    disable-block-place: true
    block-place-msg: '&f[&6Lobby&f] You''re not allowed to do that here!'
    
  join-effects:
  - speed:max:3
  - jump:max:3
  
join-motd:
  enabled: true
  motd:
    - first line
    - second line
    - third line
  
tablist:
  enabled: false
  header:
  - header
  - second line
  - third line
  footer:
  - footer
  - second line
  - third line
  
servers:
  Pirate:
    ip: localhost
    port: 25569
  Demonic:
    ip: localhost
    port: 25568
  Heroic:
    ip: localhost
    port: 25567
  Lobby:
    ip: localhost
    port: 25566
