main: me.kate.lobby.Main
name: RuthlessLobby
version: 1.0
author: Kate
description: All in one lobby plugin.
commands:
  setspawn:
    description: sets spawn
  reloadselector:
    description: reloads selector configuration
  npc:
    description: base npc command