main: me.kate.lobby.Main
name: RuthlessLobby
version: 1.0
author: Kate
description: All in one lobby plugin.
commands:
  lobby:
    description: Main help command.
  npc:
    description: base npc command.
  portal:
    description: base portal command.