# 
# Spawn coords storage
debug: false
spawn:
  x: -57
  y: 127
  z: 10
  yaw: 224.97203
  pitch: 0.014939738
options:
  world: world
  disable-plantGrowth: true
  disable-weather: true
  disable-dayLightCycle: true
  disable-mobSpawning: true
  custom-joinmsg: ' '
  custom-leavemsg: ' '
  build:
    disable-block-break: true
    block-break-msg: '&f[&6Lobby&f] You''re not allowed to do that here!'
    break-bypass-permission: lobby.breakblocks
    disable-block-place: true
    block-place-msg: '&f[&6Lobby&f] You''re not allowed to do that here!'
    place-bypass-permission: lobby.placeblocks
  join-effects:
  - speed:max:3
  - jump:max:3
  
join-motd:
  - first line
  - second line
  - third line
tablist:
  enabled: false
  header:
  - header
  - second line
  - third line
  footer:
  - footer
  - second line
  - third line
servers:
  Pirate:
    ip: localhost
    port: 25569
  Demonic:
    ip: localhost
    port: 25568
  Heroic:
    ip: localhost
    port: 25567
